/*
Deployment script for DB
CALL SQLCMD.EXE -S localhost -d master -v DatabaseName="TestDB" -i [001_CreateDatabase].sql

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
/*
--:setvar DatabaseName "IEAccountingInUSD"
*/


GO

:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END

GO

USE MASTER
PRINT N'Creating database $(DatabaseName)...';
GO
CREATE DATABASE [$(DatabaseName)] 
 CONTAINMENT = NONE 
 COLLATE Cyrillic_General_CI_AS
GO
GO


GO
PRINT N'Creating [staging]...';

GO
ALTER DATABASE [$(DatabaseName)]
    ADD FILEGROUP [staging];


PRINT N'Creating [audit]...';

GO
ALTER DATABASE [$(DatabaseName)]
    ADD FILEGROUP [audit];



PRINT N'Creating [upload]...';

GO
ALTER DATABASE [$(DatabaseName)]
    ADD FILEGROUP [upload];



USE [$(DatabaseName)] 
PRINT N'Creating all schemas...';
GO

GO
IF NOT EXISTS ( SELECT * FROM sys.schemas WHERE name = N'staging' )
    EXEC('CREATE SCHEMA [staging]');

GO
IF NOT EXISTS ( SELECT * FROM sys.schemas WHERE name = N'meta' )
    EXEC('CREATE SCHEMA [meta]');
GO
IF NOT EXISTS ( SELECT * FROM sys.schemas WHERE name = N'uts' )
    EXEC('CREATE SCHEMA [uts]');
GO

IF NOT EXISTS ( SELECT * FROM sys.schemas WHERE name = N'audit' )
    EXEC('CREATE SCHEMA [audit]');
GO

IF NOT EXISTS ( SELECT * FROM sys.schemas WHERE name = N'upload' )
    EXEC('CREATE SCHEMA [upload]');
GO

sp_configure 'show advanced options', 1;
GO
RECONFIGURE;
GO
sp_configure 'Ole Automation Procedures', 1;
GO
RECONFIGURE;

GO
EXEC master . dbo. sp_MSset_oledb_prop N'Microsoft.ACE.OLEDB.12.0' , N'AllowInProcess' , 1
GO
EXEC master . dbo. sp_MSset_oledb_prop N'Microsoft.ACE.OLEDB.12.0' , N'DynamicParameters' , 1
GO

sp_configure 'show advanced options', 1;
RECONFIGURE;
GO        
sp_configure 'Ad Hoc Distributed Queries', 1;
RECONFIGURE;
GO